# Generated by Django 4.2.1 on 2023-05-27 13:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_beautycity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='incognito_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=20, null=True, region=None, verbose_name='Телефон клиента (отказ регистрации)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reception_datetime',
            field=models.DateTimeField(db_index=True, verbose_name='Дата и время приема'),
        ),
    ]
